name: CI
on:
  pull_request:
  push:
  schedule:
  - cron: '0 14 * * 4'
jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    strategy:
      fail-fast: false
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-java@c3ac5dd0ed8db40fedb61c32fbe677e6b355e94c # v3.8.0
      with:
        java-version: 8
        distribution: adopt
    - uses: coursier/cache-action@v6
    - run: sbt -v scalafmtSbtCheck scalafmtCheckAll "+test"
