name: CI
on:
  pull_request:
  push:
  schedule:
  - cron: '0 14 * * 4'
jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    strategy:
      fail-fast: false
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-java@1df8dbefe2a8cbc99770194893dd902763bee34b # v3.9.0
      with:
        java-version: 8
        distribution: adopt
    - uses: coursier/cache-action@v6
    - run: sbt -v scalafmtSbtCheck scalafmtCheckAll "+test"
